FROM python:3.8-bullseye
COPY ./requirements.train.txt /app/requirements.txt
COPY . /app/
WORKDIR /app
RUN python -m pip install -r requirements.txt
ENTRYPOINT PYTHONUNBUFFERED=1 python vlad_model/agent_vlad_train.py
